insert into types values (1, 'IMAGE');
insert into types values (2, 'VIDEO');

insert into cat_experiencial values (1, "Golf");
insert into cat_experiencial values (2, "Playa");
insert into cat_experiencial values (3, "Rural/Naturaleza");
insert into cat_experiencial values (4, "Ocio");
insert into cat_experiencial values (5, "Compras");
insert into cat_experiencial values (6, "Gastronomía");
insert into cat_experiencial values (7, "Enoturismo");
insert into cat_experiencial values (8, "Idiomatico");
insert into cat_experiencial values (9, "Deporte");
insert into cat_experiencial values (10, "Fiestas");
insert into cat_experiencial values (11, "Lujo");
insert into cat_experiencial values (12, "Reuniones/Congresos");
insert into cat_experiencial values (13, "Ornitología");
insert into cat_experiencial values (14, "Flamenco");
insert into cat_experiencial values (15, "Cultura");
insert into cat_experiencial values (16, "Cruceros");
insert into cat_experiencial values (17, "Transportes");
insert into cat_experiencial values (18, "Actividad profesional Turismo Andaluz");

insert into cat_geografico values(null, "Almería", "Abla", null);
insert into cat_geografico values(null, "Almería", "Abrucena", null);
insert into cat_geografico values(null, "Almería", "Adra", null);
insert into cat_geografico values(null, "Almería", "Albánchez", null);
insert into cat_geografico values(null, "Almería", "Alboloduy", null);
insert into cat_geografico values(null, "Almería", "Albox", null);
insert into cat_geografico values(null, "Almería", "Alcolea", null);
insert into cat_geografico values(null, "Almería", "Alcóntar", null);
insert into cat_geografico values(null, "Almería", "Alcudia de Monteagud", null);
insert into cat_geografico values(null, "Almería", "Alhabia", null);
insert into cat_geografico values(null, "Almería", "Alhama de Almería", null);
insert into cat_geografico values(null, "Almería", "Alicún", null);
insert into cat_geografico values(null, "Almería", "Almería", null);
insert into cat_geografico values(null, "Almería", "Almócita", null);
insert into cat_geografico values(null, "Almería", "Alsodux", null);
insert into cat_geografico values(null, "Almería", "Antas", null);
insert into cat_geografico values(null, "Almería", "Arboleas", null);
insert into cat_geografico values(null, "Almería", "Armuña de Almanzora", null);
insert into cat_geografico values(null, "Almería", "Bacares", null);
insert into cat_geografico values(null, "Almería", "Bayárcal", null);
insert into cat_geografico values(null, "Almería", "Bayarque", null);
insert into cat_geografico values(null, "Almería", "Bédar", null);
insert into cat_geografico values(null, "Almería", "Beires", null);
insert into cat_geografico values(null, "Almería", "Benahadux", null);
insert into cat_geografico values(null, "Almería", "Benitagla", null);
insert into cat_geografico values(null, "Almería", "Benizalón", null);
insert into cat_geografico values(null, "Almería", "Bentarique", null);
insert into cat_geografico values(null, "Almería", "Berja", null);
insert into cat_geografico values(null, "Almería", "Canjáyar", null);
insert into cat_geografico values(null, "Almería", "Cantoria", null);
insert into cat_geografico values(null, "Almería", "Carboneras", null);
insert into cat_geografico values(null, "Almería", "Castro de Filabres", null);
insert into cat_geografico values(null, "Almería", "Cóbdar", null);
insert into cat_geografico values(null, "Almería", "Cuevas del Almanzora", null);
insert into cat_geografico values(null, "Almería", "Chercos", null);
insert into cat_geografico values(null, "Almería", "Chirivel", null);
insert into cat_geografico values(null, "Almería", "Dalías", null);
insert into cat_geografico values(null, "Almería", "Enix", null);
insert into cat_geografico values(null, "Almería", "Felix", null);
insert into cat_geografico values(null, "Almería", "Fines", null);
insert into cat_geografico values(null, "Almería", "Fiñana", null);
insert into cat_geografico values(null, "Almería", "Fondón", null);
insert into cat_geografico values(null, "Almería", "Gádor", null);
insert into cat_geografico values(null, "Almería", "Los Gallardos", null);
insert into cat_geografico values(null, "Almería", "Garrucha", null);
insert into cat_geografico values(null, "Almería", "Gérgal", null);
insert into cat_geografico values(null, "Almería", "Huécija", null);
insert into cat_geografico values(null, "Almería", "Huércal de Almería", null);
insert into cat_geografico values(null, "Almería", "Huércal-Overa", null);
insert into cat_geografico values(null, "Almería", "Illar", null);
insert into cat_geografico values(null, "Almería", "Instinción", null);
insert into cat_geografico values(null, "Almería", "Laroya", null);
insert into cat_geografico values(null, "Almería", "Láujar de Andarax", null);
insert into cat_geografico values(null, "Almería", "Líjar", null);
insert into cat_geografico values(null, "Almería", "Lubrín", null);
insert into cat_geografico values(null, "Almería", "Lucainena de las Torres", null);
insert into cat_geografico values(null, "Almería", "Lúcar", null);
insert into cat_geografico values(null, "Almería", "Macael", null);
insert into cat_geografico values(null, "Almería", "María", null);
insert into cat_geografico values(null, "Almería", "Mojácar", null);
insert into cat_geografico values(null, "Almería", "Nacimiento", null);
insert into cat_geografico values(null, "Almería", "Níjar", null);
insert into cat_geografico values(null, "Almería", "Ohanes", null);
insert into cat_geografico values(null, "Almería", "Olula de Castro", null);
insert into cat_geografico values(null, "Almería", "Olula del Río", null);
insert into cat_geografico values(null, "Almería", "Oria", null);
insert into cat_geografico values(null, "Almería", "Padules", null);
insert into cat_geografico values(null, "Almería", "Partaloa", null);
insert into cat_geografico values(null, "Almería", "Paterna del Río", null);
insert into cat_geografico values(null, "Almería", "Pechina", null);
insert into cat_geografico values(null, "Almería", "Pulpí", null);
insert into cat_geografico values(null, "Almería", "Purchena", null);
insert into cat_geografico values(null, "Almería", "Rágol", null);
insert into cat_geografico values(null, "Almería", "Rioja", null);
insert into cat_geografico values(null, "Almería", "Roquetas de Mar", null);
insert into cat_geografico values(null, "Almería", "Santa Cruz de Marchena", null);
insert into cat_geografico values(null, "Almería", "Santa Fe de Mondújar", null);
insert into cat_geografico values(null, "Almería", "Senés", null);
insert into cat_geografico values(null, "Almería", "Serón", null);
insert into cat_geografico values(null, "Almería", "Sierro", null);
insert into cat_geografico values(null, "Almería", "Somontín", null);
insert into cat_geografico values(null, "Almería", "Sorbas", null);
insert into cat_geografico values(null, "Almería", "Suflí", null);
insert into cat_geografico values(null, "Almería", "Tabernas", null);
insert into cat_geografico values(null, "Almería", "Taberno", null);
insert into cat_geografico values(null, "Almería", "Tahal", null);
insert into cat_geografico values(null, "Almería", "Terque", null);
insert into cat_geografico values(null, "Almería", "Tíjola", null);
insert into cat_geografico values(null, "Almería", "Turre", null);
insert into cat_geografico values(null, "Almería", "Turrillas", null);
insert into cat_geografico values(null, "Almería", "Uleila del Campo", null);
insert into cat_geografico values(null, "Almería", "Urrácal", null);
insert into cat_geografico values(null, "Almería", "Velefique", null);
insert into cat_geografico values(null, "Almería", "Vélez-Blanco", null);
insert into cat_geografico values(null, "Almería", "Vélez-Rubio", null);
insert into cat_geografico values(null, "Almería", "Vera", null);
insert into cat_geografico values(null, "Almería", "Viator", null);
insert into cat_geografico values(null, "Almería", "Vícar", null);
insert into cat_geografico values(null, "Almería", "Zurgena", null);
insert into cat_geografico values(null, "Almería", "Las Tres Villas", null);
insert into cat_geografico values(null, "Almería", "El Ejido", null);
insert into cat_geografico values(null, "Almería", "La Mojonera", null);
insert into cat_geografico values(null, "Almería", "Balanegra", null);
insert into cat_geografico values(null, "Cádiz", "Alcalá de los Gazules", null);
insert into cat_geografico values(null, "Cádiz", "Alcalá del Valle", null);
insert into cat_geografico values(null, "Cádiz", "Algar", null);
insert into cat_geografico values(null, "Cádiz", "Algeciras", null);
insert into cat_geografico values(null, "Cádiz", "Algodonales", null);
insert into cat_geografico values(null, "Cádiz", "Arcos de la Frontera", null);
insert into cat_geografico values(null, "Cádiz", "Barbate", null);
insert into cat_geografico values(null, "Cádiz", "Los Barrios", null);
insert into cat_geografico values(null, "Cádiz", "Benaocaz", null);
insert into cat_geografico values(null, "Cádiz", "Bornos", null);
insert into cat_geografico values(null, "Cádiz", "El Bosque", null);
insert into cat_geografico values(null, "Cádiz", "Cádiz", null);
insert into cat_geografico values(null, "Cádiz", "Castellar de la Frontera", null);
insert into cat_geografico values(null, "Cádiz", "Conil de la Frontera", null);
insert into cat_geografico values(null, "Cádiz", "Chiclana de la Frontera", null);
insert into cat_geografico values(null, "Cádiz", "Chipiona", null);
insert into cat_geografico values(null, "Cádiz", "Espera", null);
insert into cat_geografico values(null, "Cádiz", "El Gastor", null);
insert into cat_geografico values(null, "Cádiz", "Grazalema", null);
insert into cat_geografico values(null, "Cádiz", "Jerez de la Frontera", null);
insert into cat_geografico values(null, "Cádiz", "Jimena de la Frontera", null);
insert into cat_geografico values(null, "Cádiz", "La Línea de la Concepción", null);
insert into cat_geografico values(null, "Cádiz", "Medina-Sidonia", null);
insert into cat_geografico values(null, "Cádiz", "Olvera", null);
insert into cat_geografico values(null, "Cádiz", "Paterna de Rivera", null);
insert into cat_geografico values(null, "Cádiz", "Prado del Rey", null);
insert into cat_geografico values(null, "Cádiz", "El Puerto de Santa María", null);
insert into cat_geografico values(null, "Cádiz", "Puerto Real", null);
insert into cat_geografico values(null, "Cádiz", "Puerto Serrano", null);
insert into cat_geografico values(null, "Cádiz", "Rota", null);
insert into cat_geografico values(null, "Cádiz", "San Fernando", null);
insert into cat_geografico values(null, "Cádiz", "Sanlúcar de Barrameda", null);
insert into cat_geografico values(null, "Cádiz", "San Roque", null);
insert into cat_geografico values(null, "Cádiz", "Setenil de las Bodegas", null);
insert into cat_geografico values(null, "Cádiz", "Tarifa", null);
insert into cat_geografico values(null, "Cádiz", "Torre Alháquime", null);
insert into cat_geografico values(null, "Cádiz", "Trebujena", null);
insert into cat_geografico values(null, "Cádiz", "Ubrique", null);
insert into cat_geografico values(null, "Cádiz", "Vejer de la Frontera", null);
insert into cat_geografico values(null, "Cádiz", "Villaluenga del Rosario", null);
insert into cat_geografico values(null, "Cádiz", "Villamartín", null);
insert into cat_geografico values(null, "Cádiz", "Zahara", null);
insert into cat_geografico values(null, "Cádiz", "Benalup-Casas Viejas", null);
insert into cat_geografico values(null, "Cádiz", "San José del Valle", null);
insert into cat_geografico values(null, "Córdoba", "Adamuz", null);
insert into cat_geografico values(null, "Córdoba", "Aguilar de la Frontera", null);
insert into cat_geografico values(null, "Córdoba", "Alcaracejos", null);
insert into cat_geografico values(null, "Córdoba", "Almedinilla", null);
insert into cat_geografico values(null, "Córdoba", "Almodóvar del Río", null);
insert into cat_geografico values(null, "Córdoba", "Añora", null);
insert into cat_geografico values(null, "Córdoba", "Baena", null);
insert into cat_geografico values(null, "Córdoba", "Belalcázar", null);
insert into cat_geografico values(null, "Córdoba", "Belmez", null);
insert into cat_geografico values(null, "Córdoba", "Benamejí", null);
insert into cat_geografico values(null, "Córdoba", "Los Blázquez", null);
insert into cat_geografico values(null, "Córdoba", "Bujalance", null);
insert into cat_geografico values(null, "Córdoba", "Cabra", null);
insert into cat_geografico values(null, "Córdoba", "Cañete de las Torres", null);
insert into cat_geografico values(null, "Córdoba", "Carcabuey", null);
insert into cat_geografico values(null, "Córdoba", "Cardeña", null);
insert into cat_geografico values(null, "Córdoba", "La Carlota", null);
insert into cat_geografico values(null, "Córdoba", "El Carpio", null);
insert into cat_geografico values(null, "Córdoba", "Castro del Río", null);
insert into cat_geografico values(null, "Córdoba", "Conquista", null);
insert into cat_geografico values(null, "Córdoba", "Córdoba", null);
insert into cat_geografico values(null, "Córdoba", "Doña Mencía", null);
insert into cat_geografico values(null, "Córdoba", "Dos Torres", null);
insert into cat_geografico values(null, "Córdoba", "Encinas Reales", null);
insert into cat_geografico values(null, "Córdoba", "Espejo", null);
insert into cat_geografico values(null, "Córdoba", "Espiel", null);
insert into cat_geografico values(null, "Córdoba", "Fernán-Núñez", null);
insert into cat_geografico values(null, "Córdoba", "Fuente la Lancha", null);
insert into cat_geografico values(null, "Córdoba", "Fuente Obejuna", null);
insert into cat_geografico values(null, "Córdoba", "Fuente Palmera", null);
insert into cat_geografico values(null, "Córdoba", "Fuente-Tójar", null);
insert into cat_geografico values(null, "Córdoba", "La Granjuela", null);
insert into cat_geografico values(null, "Córdoba", "Guadalcázar", null);
insert into cat_geografico values(null, "Córdoba", "El Guijo", null);
insert into cat_geografico values(null, "Córdoba", "Hinojosa del Duque", null);
insert into cat_geografico values(null, "Córdoba", "Hornachuelos", null);
insert into cat_geografico values(null, "Córdoba", "Iznájar", null);
insert into cat_geografico values(null, "Córdoba", "Lucena", null);
insert into cat_geografico values(null, "Córdoba", "Luque", null);
insert into cat_geografico values(null, "Córdoba", "Montalbán de Córdoba", null);
insert into cat_geografico values(null, "Córdoba", "Montemayor", null);
insert into cat_geografico values(null, "Córdoba", "Montilla", null);
insert into cat_geografico values(null, "Córdoba", "Montoro", null);
insert into cat_geografico values(null, "Córdoba", "Monturque", null);
insert into cat_geografico values(null, "Córdoba", "Moriles", null);
insert into cat_geografico values(null, "Córdoba", "Nueva Carteya", null);
insert into cat_geografico values(null, "Córdoba", "Obejo", null);
insert into cat_geografico values(null, "Córdoba", "Palenciana", null);
insert into cat_geografico values(null, "Córdoba", "Palma del Río", null);
insert into cat_geografico values(null, "Córdoba", "Pedro Abad", null);
insert into cat_geografico values(null, "Córdoba", "Pedroche", null);
insert into cat_geografico values(null, "Córdoba", "Peñarroya-Pueblonuevo", null);
insert into cat_geografico values(null, "Córdoba", "Posadas", null);
insert into cat_geografico values(null, "Córdoba", "Pozoblanco", null);
insert into cat_geografico values(null, "Córdoba", "Priego de Córdoba", null);
insert into cat_geografico values(null, "Córdoba", "Puente Genil", null);
insert into cat_geografico values(null, "Córdoba", "La Rambla", null);
insert into cat_geografico values(null, "Córdoba", "Rute", null);
insert into cat_geografico values(null, "Córdoba", "San Sebastián de los Ballesteros", null);
insert into cat_geografico values(null, "Córdoba", "Santaella", null);
insert into cat_geografico values(null, "Córdoba", "Santa Eufemia", null);
insert into cat_geografico values(null, "Córdoba", "Torrecampo", null);
insert into cat_geografico values(null, "Córdoba", "Valenzuela", null);
insert into cat_geografico values(null, "Córdoba", "Valsequillo", null);
insert into cat_geografico values(null, "Córdoba", "La Victoria", null);
insert into cat_geografico values(null, "Córdoba", "Villa del Río", null);
insert into cat_geografico values(null, "Córdoba", "Villafranca de Córdoba", null);
insert into cat_geografico values(null, "Córdoba", "Villaharta", null);
insert into cat_geografico values(null, "Córdoba", "Villanueva de Córdoba", null);
insert into cat_geografico values(null, "Córdoba", "Villanueva del Duque", null);
insert into cat_geografico values(null, "Córdoba", "Villanueva del Rey", null);
insert into cat_geografico values(null, "Córdoba", "Villaralto", null);
insert into cat_geografico values(null, "Córdoba", "Villaviciosa de Córdoba", null);
insert into cat_geografico values(null, "Córdoba", "El Viso", null);
insert into cat_geografico values(null, "Córdoba", "Zuheros", null);
insert into cat_geografico values(null, "Granada", "Agrón", null);
insert into cat_geografico values(null, "Granada", "Alamedilla", null);
insert into cat_geografico values(null, "Granada", "Albolote", null);
insert into cat_geografico values(null, "Granada", "Albondón", null);
insert into cat_geografico values(null, "Granada", "Albuñán", null);
insert into cat_geografico values(null, "Granada", "Albuñol", null);
insert into cat_geografico values(null, "Granada", "Albuñuelas", null);
insert into cat_geografico values(null, "Granada", "Aldeire", null);
insert into cat_geografico values(null, "Granada", "Alfacar", null);
insert into cat_geografico values(null, "Granada", "Algarinejo", null);
insert into cat_geografico values(null, "Granada", "Alhama de Granada", null);
insert into cat_geografico values(null, "Granada", "Alhendín", null);
insert into cat_geografico values(null, "Granada", "Alicún de Ortega", null);
insert into cat_geografico values(null, "Granada", "Almegíjar", null);
insert into cat_geografico values(null, "Granada", "Almuñécar", null);
insert into cat_geografico values(null, "Granada", "Alquife", null);
insert into cat_geografico values(null, "Granada", "Arenas del Rey", null);
insert into cat_geografico values(null, "Granada", "Armilla", null);
insert into cat_geografico values(null, "Granada", "Atarfe", null);
insert into cat_geografico values(null, "Granada", "Baza", null);
insert into cat_geografico values(null, "Granada", "Beas de Granada", null);
insert into cat_geografico values(null, "Granada", "Beas de Guadix", null);
insert into cat_geografico values(null, "Granada", "Benalúa", null);
insert into cat_geografico values(null, "Granada", "Benalúa de las Villas", null);
insert into cat_geografico values(null, "Granada", "Benamaurel", null);
insert into cat_geografico values(null, "Granada", "Bérchules", null);
insert into cat_geografico values(null, "Granada", "Bubión", null);
insert into cat_geografico values(null, "Granada", "Busquístar", null);
insert into cat_geografico values(null, "Granada", "Cacín", null);
insert into cat_geografico values(null, "Granada", "Cádiar", null);
insert into cat_geografico values(null, "Granada", "Cájar", null);
insert into cat_geografico values(null, "Granada", "Calicasas", null);
insert into cat_geografico values(null, "Granada", "Campotéjar", null);
insert into cat_geografico values(null, "Granada", "Caniles", null);
insert into cat_geografico values(null, "Granada", "Cáñar", null);
insert into cat_geografico values(null, "Granada", "Capileira", null);
insert into cat_geografico values(null, "Granada", "Carataunas", null);
insert into cat_geografico values(null, "Granada", "Cástaras", null);
insert into cat_geografico values(null, "Granada", "Castilléjar", null);
insert into cat_geografico values(null, "Granada", "Castril", null);
insert into cat_geografico values(null, "Granada", "Cenes de la Vega", null);
insert into cat_geografico values(null, "Granada", "Cijuela", null);
insert into cat_geografico values(null, "Granada", "Cogollos de Guadix", null);
insert into cat_geografico values(null, "Granada", "Cogollos de la Vega", null);
insert into cat_geografico values(null, "Granada", "Colomera", null);
insert into cat_geografico values(null, "Granada", "Cortes de Baza", null);
insert into cat_geografico values(null, "Granada", "Cortes y Graena", null);
insert into cat_geografico values(null, "Granada", "Cúllar", null);
insert into cat_geografico values(null, "Granada", "Cúllar Vega", null);
insert into cat_geografico values(null, "Granada", "Chauchina", null);
insert into cat_geografico values(null, "Granada", "Chimeneas", null);
insert into cat_geografico values(null, "Granada", "Churriana de la Vega", null);
insert into cat_geografico values(null, "Granada", "Darro", null);
insert into cat_geografico values(null, "Granada", "Dehesas de Guadix", null);
insert into cat_geografico values(null, "Granada", "Dehesas Viejas", null);
insert into cat_geografico values(null, "Granada", "Deifontes", null);
insert into cat_geografico values(null, "Granada", "Diezma", null);
insert into cat_geografico values(null, "Granada", "Dílar", null);
insert into cat_geografico values(null, "Granada", "Dólar", null);
insert into cat_geografico values(null, "Granada", "Dúdar", null);
insert into cat_geografico values(null, "Granada", "Dúrcal", null);
insert into cat_geografico values(null, "Granada", "Escúzar", null);
insert into cat_geografico values(null, "Granada", "Ferreira", null);
insert into cat_geografico values(null, "Granada", "Fonelas", null);
insert into cat_geografico values(null, "Granada", "Freila", null);
insert into cat_geografico values(null, "Granada", "Fuente Vaqueros", null);
insert into cat_geografico values(null, "Granada", "Galera", null);
insert into cat_geografico values(null, "Granada", "Gobernador", null);
insert into cat_geografico values(null, "Granada", "Gójar", null);
insert into cat_geografico values(null, "Granada", "Gor", null);
insert into cat_geografico values(null, "Granada", "Gorafe", null);
insert into cat_geografico values(null, "Granada", "Granada", null);
insert into cat_geografico values(null, "Granada", "Guadahortuna", null);
insert into cat_geografico values(null, "Granada", "Guadix", null);
insert into cat_geografico values(null, "Granada", "Gualchos", null);
insert into cat_geografico values(null, "Granada", "Güejar Sierra", null);
insert into cat_geografico values(null, "Granada", "Güevéjar", null);
insert into cat_geografico values(null, "Granada", "Huélago", null);
insert into cat_geografico values(null, "Granada", "Huéneja", null);
insert into cat_geografico values(null, "Granada", "Huéscar", null);
insert into cat_geografico values(null, "Granada", "Huétor de Santillán", null);
insert into cat_geografico values(null, "Granada", "Huétor Tájar", null);
insert into cat_geografico values(null, "Granada", "Huétor Vega", null);
insert into cat_geografico values(null, "Granada", "Íllora", null);
insert into cat_geografico values(null, "Granada", "Ítrabo", null);
insert into cat_geografico values(null, "Granada", "Iznalloz", null);
insert into cat_geografico values(null, "Granada", "Játar", null);
insert into cat_geografico values(null, "Granada", "Jayena", null);
insert into cat_geografico values(null, "Granada", "Jerez del Marquesado", null);
insert into cat_geografico values(null, "Granada", "Jete", null);
insert into cat_geografico values(null, "Granada", "Jun", null);
insert into cat_geografico values(null, "Granada", "Juviles", null);
insert into cat_geografico values(null, "Granada", "La Calahorra", null);
insert into cat_geografico values(null, "Granada", "Láchar", null);
insert into cat_geografico values(null, "Granada", "Lanjarón", null);
insert into cat_geografico values(null, "Granada", "Lanteira", null);
insert into cat_geografico values(null, "Granada", "Lecrín", null);
insert into cat_geografico values(null, "Granada", "Lentegí", null);
insert into cat_geografico values(null, "Granada", "Lobras", null);
insert into cat_geografico values(null, "Granada", "Loja", null);
insert into cat_geografico values(null, "Granada", "Lugros", null);
insert into cat_geografico values(null, "Granada", "Lújar", null);
insert into cat_geografico values(null, "Granada", "La Malahá", null);
insert into cat_geografico values(null, "Granada", "Maracena", null);
insert into cat_geografico values(null, "Granada", "Marchal", null);
insert into cat_geografico values(null, "Granada", "Moclín", null);
insert into cat_geografico values(null, "Granada", "Molvízar", null);
insert into cat_geografico values(null, "Granada", "Monachil", null);
insert into cat_geografico values(null, "Granada", "Montefrío", null);
insert into cat_geografico values(null, "Granada", "Montejícar", null);
insert into cat_geografico values(null, "Granada", "Montillana", null);
insert into cat_geografico values(null, "Granada", "Moraleda de Zafayona", null);
insert into cat_geografico values(null, "Granada", "Motril", null);
insert into cat_geografico values(null, "Granada", "Murtas", null);
insert into cat_geografico values(null, "Granada", "Nigüelas", null);
insert into cat_geografico values(null, "Granada", "Nívar", null);
insert into cat_geografico values(null, "Granada", "Ogíjares", null);
insert into cat_geografico values(null, "Granada", "Orce", null);
insert into cat_geografico values(null, "Granada", "Órgiva", null);
insert into cat_geografico values(null, "Granada", "Otívar", null);
insert into cat_geografico values(null, "Granada", "Villa de Otura", null);
insert into cat_geografico values(null, "Granada", "Padul", null);
insert into cat_geografico values(null, "Granada", "Pampaneira", null);
insert into cat_geografico values(null, "Granada", "Pedro Martínez", null);
insert into cat_geografico values(null, "Granada", "Peligros", null);
insert into cat_geografico values(null, "Granada", "La Peza", null);
insert into cat_geografico values(null, "Granada", "Pinos Genil", null);
insert into cat_geografico values(null, "Granada", "Pinos Puente", null);
insert into cat_geografico values(null, "Granada", "Piñar", null);
insert into cat_geografico values(null, "Granada", "Polícar", null);
insert into cat_geografico values(null, "Granada", "Polopos", null);
insert into cat_geografico values(null, "Granada", "Pórtugos", null);
insert into cat_geografico values(null, "Granada", "Puebla de Don Fadrique", null);
insert into cat_geografico values(null, "Granada", "Pulianas", null);
insert into cat_geografico values(null, "Granada", "Purullena", null);
insert into cat_geografico values(null, "Granada", "Quéntar", null);
insert into cat_geografico values(null, "Granada", "Rubite", null);
insert into cat_geografico values(null, "Granada", "Salar", null);
insert into cat_geografico values(null, "Granada", "Salobreña", null);
insert into cat_geografico values(null, "Granada", "Santa Cruz del Comercio", null);
insert into cat_geografico values(null, "Granada", "Santa Fe", null);
insert into cat_geografico values(null, "Granada", "Soportújar", null);
insert into cat_geografico values(null, "Granada", "Sorvilán", null);
insert into cat_geografico values(null, "Granada", "Torre-Cardela", null);
insert into cat_geografico values(null, "Granada", "Torvizcón", null);
insert into cat_geografico values(null, "Granada", "Trevélez", null);
insert into cat_geografico values(null, "Granada", "Turón", null);
insert into cat_geografico values(null, "Granada", "Ugíjar", null);
insert into cat_geografico values(null, "Granada", "Válor", null);
insert into cat_geografico values(null, "Granada", "Vélez de Benaudalla", null);
insert into cat_geografico values(null, "Granada", "Ventas de Huelma", null);
insert into cat_geografico values(null, "Granada", "Villanueva de las Torres", null);
insert into cat_geografico values(null, "Granada", "Villanueva Mesía", null);
insert into cat_geografico values(null, "Granada", "Víznar", null);
insert into cat_geografico values(null, "Granada", "Zafarraya", null);
insert into cat_geografico values(null, "Granada", "La Zubia", null);
insert into cat_geografico values(null, "Granada", "Zújar", null);
insert into cat_geografico values(null, "Granada", "La Taha", null);
insert into cat_geografico values(null, "Granada", "El Valle", null);
insert into cat_geografico values(null, "Granada", "Nevada", null);
insert into cat_geografico values(null, "Granada", "Alpujarra de la Sierra", null);
insert into cat_geografico values(null, "Granada", "Las Gabias", null);
insert into cat_geografico values(null, "Granada", "Los Guájares", null);
insert into cat_geografico values(null, "Granada", "Valle del Zalabí", null);
insert into cat_geografico values(null, "Granada", "Villamena", null);
insert into cat_geografico values(null, "Granada", "Morelábor", null);
insert into cat_geografico values(null, "Granada", "El Pinar", null);
insert into cat_geografico values(null, "Granada", "Vegas del Genil", null);
insert into cat_geografico values(null, "Granada", "Cuevas del Campo", null);
insert into cat_geografico values(null, "Granada", "Zagra", null);
insert into cat_geografico values(null, "Granada", "Valderrubio", null);
insert into cat_geografico values(null, "Granada", "Domingo Pérez de Granada", null);
insert into cat_geografico values(null, "Huelva", "Alájar", null);
insert into cat_geografico values(null, "Huelva", "Aljaraque", null);
insert into cat_geografico values(null, "Huelva", "El Almendro", null);
insert into cat_geografico values(null, "Huelva", "Almonaster la Real", null);
insert into cat_geografico values(null, "Huelva", "Almonte", null);
insert into cat_geografico values(null, "Huelva", "Alosno", null);
insert into cat_geografico values(null, "Huelva", "Aracena", null);
insert into cat_geografico values(null, "Huelva", "Aroche", null);
insert into cat_geografico values(null, "Huelva", "Arroyomolinos de León", null);
insert into cat_geografico values(null, "Huelva", "Ayamonte", null);
insert into cat_geografico values(null, "Huelva", "Beas", null);
insert into cat_geografico values(null, "Huelva", "Berrocal", null);
insert into cat_geografico values(null, "Huelva", "Bollullos Par del Condado", null);
insert into cat_geografico values(null, "Huelva", "Bonares", null);
insert into cat_geografico values(null, "Huelva", "Cabezas Rubias", null);
insert into cat_geografico values(null, "Huelva", "Cala", null);
insert into cat_geografico values(null, "Huelva", "Calañas", null);
insert into cat_geografico values(null, "Huelva", "El Campillo", null);
insert into cat_geografico values(null, "Huelva", "Campofrío", null);
insert into cat_geografico values(null, "Huelva", "Cañaveral de León", null);
insert into cat_geografico values(null, "Huelva", "Cartaya", null);
insert into cat_geografico values(null, "Huelva", "Castaño del Robledo", null);
insert into cat_geografico values(null, "Huelva", "El Cerro de Andévalo", null);
insert into cat_geografico values(null, "Huelva", "Corteconcepción", null);
insert into cat_geografico values(null, "Huelva", "Cortegana", null);
insert into cat_geografico values(null, "Huelva", "Cortelazor", null);
insert into cat_geografico values(null, "Huelva", "Cumbres de Enmedio", null);
insert into cat_geografico values(null, "Huelva", "Cumbres de San Bartolomé", null);
insert into cat_geografico values(null, "Huelva", "Cumbres Mayores", null);
insert into cat_geografico values(null, "Huelva", "Chucena", null);
insert into cat_geografico values(null, "Huelva", "Encinasola", null);
insert into cat_geografico values(null, "Huelva", "Escacena del Campo", null);
insert into cat_geografico values(null, "Huelva", "Fuenteheridos", null);
insert into cat_geografico values(null, "Huelva", "Galaroza", null);
insert into cat_geografico values(null, "Huelva", "Gibraleón", null);
insert into cat_geografico values(null, "Huelva", "La Granada de Río-Tinto", null);
insert into cat_geografico values(null, "Huelva", "El Granado", null);
insert into cat_geografico values(null, "Huelva", "Higuera de la Sierra", null);
insert into cat_geografico values(null, "Huelva", "Hinojales", null);
insert into cat_geografico values(null, "Huelva", "Hinojos", null);
insert into cat_geografico values(null, "Huelva", "Huelva", null);
insert into cat_geografico values(null, "Huelva", "Isla Cristina", null);
insert into cat_geografico values(null, "Huelva", "Jabugo", null);
insert into cat_geografico values(null, "Huelva", "Lepe", null);
insert into cat_geografico values(null, "Huelva", "Linares de la Sierra", null);
insert into cat_geografico values(null, "Huelva", "Lucena del Puerto", null);
insert into cat_geografico values(null, "Huelva", "Manzanilla", null);
insert into cat_geografico values(null, "Huelva", "Los Marines", null);
insert into cat_geografico values(null, "Huelva", "Minas de Riotinto", null);
insert into cat_geografico values(null, "Huelva", "Moguer", null);
insert into cat_geografico values(null, "Huelva", "La Nava", null);
insert into cat_geografico values(null, "Huelva", "Nerva", null);
insert into cat_geografico values(null, "Huelva", "Niebla", null);
insert into cat_geografico values(null, "Huelva", "La Palma del Condado", null);
insert into cat_geografico values(null, "Huelva", "Palos de la Frontera", null);
insert into cat_geografico values(null, "Huelva", "Paterna del Campo", null);
insert into cat_geografico values(null, "Huelva", "Paymogo", null);
insert into cat_geografico values(null, "Huelva", "Puebla de Guzmán", null);
insert into cat_geografico values(null, "Huelva", "Puerto Moral", null);
insert into cat_geografico values(null, "Huelva", "Punta Umbría", null);
insert into cat_geografico values(null, "Huelva", "Rociana del Condado", null);
insert into cat_geografico values(null, "Huelva", "Rosal de la Frontera", null);
insert into cat_geografico values(null, "Huelva", "San Bartolomé de la Torre", null);
insert into cat_geografico values(null, "Huelva", "San Juan del Puerto", null);
insert into cat_geografico values(null, "Huelva", "Sanlúcar de Guadiana", null);
insert into cat_geografico values(null, "Huelva", "San Silvestre de Guzmán", null);
insert into cat_geografico values(null, "Huelva", "Santa Ana la Real", null);
insert into cat_geografico values(null, "Huelva", "Santa Bárbara de Casa", null);
insert into cat_geografico values(null, "Huelva", "Santa Olalla del Cala", null);
insert into cat_geografico values(null, "Huelva", "Trigueros", null);
insert into cat_geografico values(null, "Huelva", "Valdelarco", null);
insert into cat_geografico values(null, "Huelva", "Valverde del Camino", null);
insert into cat_geografico values(null, "Huelva", "Villablanca", null);
insert into cat_geografico values(null, "Huelva", "Villalba del Alcor", null);
insert into cat_geografico values(null, "Huelva", "Villanueva de las Cruces", null);
insert into cat_geografico values(null, "Huelva", "Villanueva de los Castillejos", null);
insert into cat_geografico values(null, "Huelva", "Villarrasa", null);
insert into cat_geografico values(null, "Huelva", "Zalamea la Real", null);
insert into cat_geografico values(null, "Huelva", "Zufre", null);
insert into cat_geografico values(null, "Jaén", "Albánchez de Mágina", null);
insert into cat_geografico values(null, "Jaén", "Alcalá la Real", null);
insert into cat_geografico values(null, "Jaén", "Alcaudete", null);
insert into cat_geografico values(null, "Jaén", "Aldeaquemada", null);
insert into cat_geografico values(null, "Jaén", "Andújar", null);
insert into cat_geografico values(null, "Jaén", "Arjona", null);
insert into cat_geografico values(null, "Jaén", "Arjonilla", null);
insert into cat_geografico values(null, "Jaén", "Arquillos", null);
insert into cat_geografico values(null, "Jaén", "Baeza", null);
insert into cat_geografico values(null, "Jaén", "Bailén", null);
insert into cat_geografico values(null, "Jaén", "Baños de la Encina", null);
insert into cat_geografico values(null, "Jaén", "Beas de Segura", null);
insert into cat_geografico values(null, "Jaén", "Begíjar", null);
insert into cat_geografico values(null, "Jaén", "Bélmez de la Moraleda", null);
insert into cat_geografico values(null, "Jaén", "Benatae", null);
insert into cat_geografico values(null, "Jaén", "Cabra de Santo Cristo", null);
insert into cat_geografico values(null, "Jaén", "Cambil", null);
insert into cat_geografico values(null, "Jaén", "Campillo de Arenas", null);
insert into cat_geografico values(null, "Jaén", "Canena", null);
insert into cat_geografico values(null, "Jaén", "Carboneros", null);
insert into cat_geografico values(null, "Jaén", "La Carolina", null);
insert into cat_geografico values(null, "Jaén", "Castellar", null);
insert into cat_geografico values(null, "Jaén", "Castillo de Locubín", null);
insert into cat_geografico values(null, "Jaén", "Cazalilla", null);
insert into cat_geografico values(null, "Jaén", "Cazorla", null);
insert into cat_geografico values(null, "Jaén", "Chiclana de Segura", null);
insert into cat_geografico values(null, "Jaén", "Chilluévar", null);
insert into cat_geografico values(null, "Jaén", "Escañuela", null);
insert into cat_geografico values(null, "Jaén", "Espelúy", null);
insert into cat_geografico values(null, "Jaén", "Frailes", null);
insert into cat_geografico values(null, "Jaén", "Fuensanta de Martos", null);
insert into cat_geografico values(null, "Jaén", "Fuerte del Rey", null);
insert into cat_geografico values(null, "Jaén", "Génave", null);
insert into cat_geografico values(null, "Jaén", "La Guardia de Jaén", null);
insert into cat_geografico values(null, "Jaén", "Guarromán", null);
insert into cat_geografico values(null, "Jaén", "Lahiguera", null);
insert into cat_geografico values(null, "Jaén", "Higuera de Calatrava", null);
insert into cat_geografico values(null, "Jaén", "Hinojares", null);
insert into cat_geografico values(null, "Jaén", "Hornos", null);
insert into cat_geografico values(null, "Jaén", "Huelma", null);
insert into cat_geografico values(null, "Jaén", "Huesa", null);
insert into cat_geografico values(null, "Jaén", "Ibros", null);
insert into cat_geografico values(null, "Jaén", "La Iruela", null);
insert into cat_geografico values(null, "Jaén", "Iznatoraf", null);
insert into cat_geografico values(null, "Jaén", "Jabalquinto", null);
insert into cat_geografico values(null, "Jaén", "Jaén", null);
insert into cat_geografico values(null, "Jaén", "Jamilena", null);
insert into cat_geografico values(null, "Jaén", "Jimena", null);
insert into cat_geografico values(null, "Jaén", "Jódar", null);
insert into cat_geografico values(null, "Jaén", "Larva", null);
insert into cat_geografico values(null, "Jaén", "Linares", null);
insert into cat_geografico values(null, "Jaén", "Lopera", null);
insert into cat_geografico values(null, "Jaén", "Lupión", null);
insert into cat_geografico values(null, "Jaén", "Mancha Real", null);
insert into cat_geografico values(null, "Jaén", "Marmolejo", null);
insert into cat_geografico values(null, "Jaén", "Martos", null);
insert into cat_geografico values(null, "Jaén", "Mengíbar", null);
insert into cat_geografico values(null, "Jaén", "Montizón", null);
insert into cat_geografico values(null, "Jaén", "Navas de San Juan", null);
insert into cat_geografico values(null, "Jaén", "Noalejo", null);
insert into cat_geografico values(null, "Jaén", "Orcera", null);
insert into cat_geografico values(null, "Jaén", "Peal de Becerro", null);
insert into cat_geografico values(null, "Jaén", "Pegalajar", null);
insert into cat_geografico values(null, "Jaén", "Porcuna", null);
insert into cat_geografico values(null, "Jaén", "Pozo Alcón", null);
insert into cat_geografico values(null, "Jaén", "Puente de Génave", null);
insert into cat_geografico values(null, "Jaén", "La Puerta de Segura", null);
insert into cat_geografico values(null, "Jaén", "Quesada", null);
insert into cat_geografico values(null, "Jaén", "Rus", null);
insert into cat_geografico values(null, "Jaén", "Sabiote", null);
insert into cat_geografico values(null, "Jaén", "Santa Elena", null);
insert into cat_geografico values(null, "Jaén", "Santiago de Calatrava", null);
insert into cat_geografico values(null, "Jaén", "Santisteban del Puerto", null);
insert into cat_geografico values(null, "Jaén", "Santo Tomé", null);
insert into cat_geografico values(null, "Jaén", "Segura de la Sierra", null);
insert into cat_geografico values(null, "Jaén", "Siles", null);
insert into cat_geografico values(null, "Jaén", "Sorihuela del Guadalimar", null);
insert into cat_geografico values(null, "Jaén", "Torreblascopedro", null);
insert into cat_geografico values(null, "Jaén", "Torredelcampo", null);
insert into cat_geografico values(null, "Jaén", "Torredonjimeno", null);
insert into cat_geografico values(null, "Jaén", "Torreperogil", null);
insert into cat_geografico values(null, "Jaén", "Torres", null);
insert into cat_geografico values(null, "Jaén", "Torres de Albánchez", null);
insert into cat_geografico values(null, "Jaén", "Úbeda", null);
insert into cat_geografico values(null, "Jaén", "Valdepeñas de Jaén", null);
insert into cat_geografico values(null, "Jaén", "Vilches", null);
insert into cat_geografico values(null, "Jaén", "Villacarrillo", null);
insert into cat_geografico values(null, "Jaén", "Villanueva de la Reina", null);
insert into cat_geografico values(null, "Jaén", "Villanueva del Arzobispo", null);
insert into cat_geografico values(null, "Jaén", "Villardompardo", null);
insert into cat_geografico values(null, "Jaén", "Los Villares", null);
insert into cat_geografico values(null, "Jaén", "Villarrodrigo", null);
insert into cat_geografico values(null, "Jaén", "Cárcheles", null);
insert into cat_geografico values(null, "Jaén", "Bedmar y Garcíez", null);
insert into cat_geografico values(null, "Jaén", "Villatorres", null);
insert into cat_geografico values(null, "Jaén", "Santiago-Pontones", null);
insert into cat_geografico values(null, "Jaén", "Arroyo del Ojanco", null);
insert into cat_geografico values(null, "Málaga", "Alameda", null);
insert into cat_geografico values(null, "Málaga", "Alcaucín", null);
insert into cat_geografico values(null, "Málaga", "Alfarnate", null);
insert into cat_geografico values(null, "Málaga", "Alfarnatejo", null);
insert into cat_geografico values(null, "Málaga", "Algarrobo", null);
insert into cat_geografico values(null, "Málaga", "Algatocín", null);
insert into cat_geografico values(null, "Málaga", "Alhaurín de la Torre", null);
insert into cat_geografico values(null, "Málaga", "Alhaurín el Grande", null);
insert into cat_geografico values(null, "Málaga", "Almáchar", null);
insert into cat_geografico values(null, "Málaga", "Almargen", null);
insert into cat_geografico values(null, "Málaga", "Almogía", null);
insert into cat_geografico values(null, "Málaga", "Álora", null);
insert into cat_geografico values(null, "Málaga", "Alozaina", null);
insert into cat_geografico values(null, "Málaga", "Alpandeire", null);
insert into cat_geografico values(null, "Málaga", "Antequera", null);
insert into cat_geografico values(null, "Málaga", "Árchez", null);
insert into cat_geografico values(null, "Málaga", "Archidona", null);
insert into cat_geografico values(null, "Málaga", "Ardales", null);
insert into cat_geografico values(null, "Málaga", "Arenas", null);
insert into cat_geografico values(null, "Málaga", "Arriate", null);
insert into cat_geografico values(null, "Málaga", "Atajate", null);
insert into cat_geografico values(null, "Málaga", "Benadalid", null);
insert into cat_geografico values(null, "Málaga", "Benahavís", null);
insert into cat_geografico values(null, "Málaga", "Benalauría", null);
insert into cat_geografico values(null, "Málaga", "Benalmádena", null);
insert into cat_geografico values(null, "Málaga", "Benamargosa", null);
insert into cat_geografico values(null, "Málaga", "Benamocarra", null);
insert into cat_geografico values(null, "Málaga", "Benaoján", null);
insert into cat_geografico values(null, "Málaga", "Benarrabá", null);
insert into cat_geografico values(null, "Málaga", "El Borge", null);
insert into cat_geografico values(null, "Málaga", "El Burgo", null);
insert into cat_geografico values(null, "Málaga", "Campillos", null);
insert into cat_geografico values(null, "Málaga", "Canillas de Aceituno", null);
insert into cat_geografico values(null, "Málaga", "Canillas de Albaida", null);
insert into cat_geografico values(null, "Málaga", "Cañete la Real", null);
insert into cat_geografico values(null, "Málaga", "Carratraca", null);
insert into cat_geografico values(null, "Málaga", "Cartajima", null);
insert into cat_geografico values(null, "Málaga", "Cártama", null);
insert into cat_geografico values(null, "Málaga", "Casabermeja", null);
insert into cat_geografico values(null, "Málaga", "Casarabonela", null);
insert into cat_geografico values(null, "Málaga", "Casares", null);
insert into cat_geografico values(null, "Málaga", "Coín", null);
insert into cat_geografico values(null, "Málaga", "Colmenar", null);
insert into cat_geografico values(null, "Málaga", "Comares", null);
insert into cat_geografico values(null, "Málaga", "Cómpeta", null);
insert into cat_geografico values(null, "Málaga", "Cortes de la Frontera", null);
insert into cat_geografico values(null, "Málaga", "Cuevas Bajas", null);
insert into cat_geografico values(null, "Málaga", "Cuevas del Becerro", null);
insert into cat_geografico values(null, "Málaga", "Cuevas de San Marcos", null);
insert into cat_geografico values(null, "Málaga", "Cútar", null);
insert into cat_geografico values(null, "Málaga", "Estepona", null);
insert into cat_geografico values(null, "Málaga", "Faraján", null);
insert into cat_geografico values(null, "Málaga", "Frigiliana", null);
insert into cat_geografico values(null, "Málaga", "Fuengirola", null);
insert into cat_geografico values(null, "Málaga", "Fuente de Piedra", null);
insert into cat_geografico values(null, "Málaga", "Gaucín", null);
insert into cat_geografico values(null, "Málaga", "Genalguacil", null);
insert into cat_geografico values(null, "Málaga", "Guaro", null);
insert into cat_geografico values(null, "Málaga", "Humilladero", null);
insert into cat_geografico values(null, "Málaga", "Igualeja", null);
insert into cat_geografico values(null, "Málaga", "Istán", null);
insert into cat_geografico values(null, "Málaga", "Iznate", null);
insert into cat_geografico values(null, "Málaga", "Jimera de Líbar", null);
insert into cat_geografico values(null, "Málaga", "Jubrique", null);
insert into cat_geografico values(null, "Málaga", "Júzcar", null);
insert into cat_geografico values(null, "Málaga", "Macharaviaya", null);
insert into cat_geografico values(null, "Málaga", "Málaga", null);
insert into cat_geografico values(null, "Málaga", "Manilva", null);
insert into cat_geografico values(null, "Málaga", "Marbella", null);
insert into cat_geografico values(null, "Málaga", "Mijas", null);
insert into cat_geografico values(null, "Málaga", "Moclinejo", null);
insert into cat_geografico values(null, "Málaga", "Mollina", null);
insert into cat_geografico values(null, "Málaga", "Monda", null);
insert into cat_geografico values(null, "Málaga", "Montejaque", null);
insert into cat_geografico values(null, "Málaga", "Nerja", null);
insert into cat_geografico values(null, "Málaga", "Ojén", null);
insert into cat_geografico values(null, "Málaga", "Parauta", null);
insert into cat_geografico values(null, "Málaga", "Periana", null);
insert into cat_geografico values(null, "Málaga", "Pizarra", null);
insert into cat_geografico values(null, "Málaga", "Pujerra", null);
insert into cat_geografico values(null, "Málaga", "Rincón de la Victoria", null);
insert into cat_geografico values(null, "Málaga", "Riogordo", null);
insert into cat_geografico values(null, "Málaga", "Ronda", null);
insert into cat_geografico values(null, "Málaga", "Salares", null);
insert into cat_geografico values(null, "Málaga", "Sayalonga", null);
insert into cat_geografico values(null, "Málaga", "Sedella", null);
insert into cat_geografico values(null, "Málaga", "Sierra de Yeguas", null);
insert into cat_geografico values(null, "Málaga", "Teba", null);
insert into cat_geografico values(null, "Málaga", "Tolox", null);
insert into cat_geografico values(null, "Málaga", "Torrox", null);
insert into cat_geografico values(null, "Málaga", "Totalán", null);
insert into cat_geografico values(null, "Málaga", "Valle de Abdalajís", null);
insert into cat_geografico values(null, "Málaga", "Vélez-Málaga", null);
insert into cat_geografico values(null, "Málaga", "Villanueva de Algaidas", null);
insert into cat_geografico values(null, "Málaga", "Villanueva del Rosario", null);
insert into cat_geografico values(null, "Málaga", "Villanueva del Trabuco", null);
insert into cat_geografico values(null, "Málaga", "Villanueva de Tapia", null);
insert into cat_geografico values(null, "Málaga", "Viñuela", null);
insert into cat_geografico values(null, "Málaga", "Yunquera", null);
insert into cat_geografico values(null, "Málaga", "Torremolinos", null);
insert into cat_geografico values(null, "Málaga", "Villanueva de la Concepción", null);
insert into cat_geografico values(null, "Málaga", "Montecorto", null);
insert into cat_geografico values(null, "Málaga", "Serrato", null);
insert into cat_geografico values(null, "Sevilla", "Aguadulce", null);
insert into cat_geografico values(null, "Sevilla", "Alanís", null);
insert into cat_geografico values(null, "Sevilla", "Albaida del Aljarafe", null);
insert into cat_geografico values(null, "Sevilla", "Alcalá de Guadaíra", null);
insert into cat_geografico values(null, "Sevilla", "Alcalá del Río", null);
insert into cat_geografico values(null, "Sevilla", "Alcolea del Río", null);
insert into cat_geografico values(null, "Sevilla", "La Algaba", null);
insert into cat_geografico values(null, "Sevilla", "Algámitas", null);
insert into cat_geografico values(null, "Sevilla", "Almadén de la Plata", null);
insert into cat_geografico values(null, "Sevilla", "Almensilla", null);
insert into cat_geografico values(null, "Sevilla", "Arahal", null);
insert into cat_geografico values(null, "Sevilla", "Aznalcázar", null);
insert into cat_geografico values(null, "Sevilla", "Aznalcóllar", null);
insert into cat_geografico values(null, "Sevilla", "Badolatosa", null);
insert into cat_geografico values(null, "Sevilla", "Benacazón", null);
insert into cat_geografico values(null, "Sevilla", "Bollullos de la Mitación", null);
insert into cat_geografico values(null, "Sevilla", "Bormujos", null);
insert into cat_geografico values(null, "Sevilla", "Brenes", null);
insert into cat_geografico values(null, "Sevilla", "Burguillos", null);
insert into cat_geografico values(null, "Sevilla", "Las Cabezas de San Juan", null);
insert into cat_geografico values(null, "Sevilla", "Camas", null);
insert into cat_geografico values(null, "Sevilla", "La Campana", null);
insert into cat_geografico values(null, "Sevilla", "Cantillana", null);
insert into cat_geografico values(null, "Sevilla", "Carmona", null);
insert into cat_geografico values(null, "Sevilla", "Carrión de los Céspedes", null);
insert into cat_geografico values(null, "Sevilla", "Casariche", null);
insert into cat_geografico values(null, "Sevilla", "Castiblanco de los Arroyos", null);
insert into cat_geografico values(null, "Sevilla", "Castilleja de Guzmán", null);
insert into cat_geografico values(null, "Sevilla", "Castilleja de la Cuesta", null);
insert into cat_geografico values(null, "Sevilla", "Castilleja del Campo", null);
insert into cat_geografico values(null, "Sevilla", "El Castillo de las Guardas", null);
insert into cat_geografico values(null, "Sevilla", "Cazalla de la Sierra", null);
insert into cat_geografico values(null, "Sevilla", "Constantina", null);
insert into cat_geografico values(null, "Sevilla", "Coria del Río", null);
insert into cat_geografico values(null, "Sevilla", "Coripe", null);
insert into cat_geografico values(null, "Sevilla", "El Coronil", null);
insert into cat_geografico values(null, "Sevilla", "Los Corrales", null);
insert into cat_geografico values(null, "Sevilla", "Dos Hermanas", null);
insert into cat_geografico values(null, "Sevilla", "Écija", null);
insert into cat_geografico values(null, "Sevilla", "Espartinas", null);
insert into cat_geografico values(null, "Sevilla", "Estepa", null);
insert into cat_geografico values(null, "Sevilla", "Fuentes de Andalucía", null);
insert into cat_geografico values(null, "Sevilla", "El Garrobo", null);
insert into cat_geografico values(null, "Sevilla", "Gelves", null);
insert into cat_geografico values(null, "Sevilla", "Gerena", null);
insert into cat_geografico values(null, "Sevilla", "Gilena", null);
insert into cat_geografico values(null, "Sevilla", "Gines", null);
insert into cat_geografico values(null, "Sevilla", "Guadalcanal", null);
insert into cat_geografico values(null, "Sevilla", "Guillena", null);
insert into cat_geografico values(null, "Sevilla", "Herrera", null);
insert into cat_geografico values(null, "Sevilla", "Huévar del Aljarafe", null);
insert into cat_geografico values(null, "Sevilla", "Lantejuela", null);
insert into cat_geografico values(null, "Sevilla", "Lebrija", null);
insert into cat_geografico values(null, "Sevilla", "Lora de Estepa", null);
insert into cat_geografico values(null, "Sevilla", "Lora del Río", null);
insert into cat_geografico values(null, "Sevilla", "La Luisiana", null);
insert into cat_geografico values(null, "Sevilla", "El Madroño", null);
insert into cat_geografico values(null, "Sevilla", "Mairena del Alcor", null);
insert into cat_geografico values(null, "Sevilla", "Mairena del Aljarafe", null);
insert into cat_geografico values(null, "Sevilla", "Marchena", null);
insert into cat_geografico values(null, "Sevilla", "Marinaleda", null);
insert into cat_geografico values(null, "Sevilla", "Martín de la Jara", null);
insert into cat_geografico values(null, "Sevilla", "Los Molares", null);
insert into cat_geografico values(null, "Sevilla", "Montellano", null);
insert into cat_geografico values(null, "Sevilla", "Morón de la Frontera", null);
insert into cat_geografico values(null, "Sevilla", "Las Navas de la Concepción", null);
insert into cat_geografico values(null, "Sevilla", "Olivares", null);
insert into cat_geografico values(null, "Sevilla", "Osuna", null);
insert into cat_geografico values(null, "Sevilla", "Los Palacios y Villafranca", null);
insert into cat_geografico values(null, "Sevilla", "Palomares del Río", null);
insert into cat_geografico values(null, "Sevilla", "Paradas", null);
insert into cat_geografico values(null, "Sevilla", "Pedrera", null);
insert into cat_geografico values(null, "Sevilla", "El Pedroso", null);
insert into cat_geografico values(null, "Sevilla", "Peñaflor", null);
insert into cat_geografico values(null, "Sevilla", "Pilas", null);
insert into cat_geografico values(null, "Sevilla", "Pruna", null);
insert into cat_geografico values(null, "Sevilla", "La Puebla de Cazalla", null);
insert into cat_geografico values(null, "Sevilla", "La Puebla de los Infantes", null);
insert into cat_geografico values(null, "Sevilla", "La Puebla del Río", null);
insert into cat_geografico values(null, "Sevilla", "El Real de la Jara", null);
insert into cat_geografico values(null, "Sevilla", "La Rinconada", null);
insert into cat_geografico values(null, "Sevilla", "La Roda de Andalucía", null);
insert into cat_geografico values(null, "Sevilla", "El Ronquillo", null);
insert into cat_geografico values(null, "Sevilla", "El Rubio", null);
insert into cat_geografico values(null, "Sevilla", "Salteras", null);
insert into cat_geografico values(null, "Sevilla", "San Juan de Aznalfarache", null);
insert into cat_geografico values(null, "Sevilla", "Sanlúcar la Mayor", null);
insert into cat_geografico values(null, "Sevilla", "San Nicolás del Puerto", null);
insert into cat_geografico values(null, "Sevilla", "Santiponce", null);
insert into cat_geografico values(null, "Sevilla", "El Saucejo", null);
insert into cat_geografico values(null, "Sevilla", "Sevilla", null);
insert into cat_geografico values(null, "Sevilla", "Tocina", null);
insert into cat_geografico values(null, "Sevilla", "Tomares", null);
insert into cat_geografico values(null, "Sevilla", "Umbrete", null);
insert into cat_geografico values(null, "Sevilla", "Utrera", null);
insert into cat_geografico values(null, "Sevilla", "Valencina de la Concepción", null);
insert into cat_geografico values(null, "Sevilla", "Villamanrique de la Condesa", null);
insert into cat_geografico values(null, "Sevilla", "Villanueva del Ariscal", null);
insert into cat_geografico values(null, "Sevilla", "Villanueva del Río y Minas", null);
insert into cat_geografico values(null, "Sevilla", "Villanueva de San Juan", null);
insert into cat_geografico values(null, "Sevilla", "Villaverde del Río", null);
insert into cat_geografico values(null, "Sevilla", "El Viso del Alcor", null);
insert into cat_geografico values(null, "Sevilla", "Cañada Rosal", null);
insert into cat_geografico values(null, "Sevilla", "Isla Mayor", null);
insert into cat_geografico values(null, "Sevilla", "El Cuervo de Sevilla", null);

insert into cat_temporal values (1, "Primavera");
insert into cat_temporal values (2, "Verano");
insert into cat_temporal values (3, "Otoño");
insert into cat_temporal values (4, "Invierno");
insert into cat_temporal values (5, "Navidad");
insert into cat_temporal values (6, "Semana Santa");

insert into cat_vivencial values (1, "Seniors");
insert into cat_vivencial values (2, "Jóvenes");
insert into cat_vivencial values (3, "Familias");
insert into cat_vivencial values (4, "Singles");
insert into cat_vivencial values (5, "Lgtb");
insert into cat_vivencial values (6, "Negocios");
